### PR TITLE
get rid of ++ applied to bool so that it compiles with g++-11

### PR DESCRIPTION
**Pull request by araujoms**

### CODE REVIEW

**Comment by denisrosset** [comment]
It seems that the code is actually "counting" using a bool, because of the name of the variable (count non zeros).

But anyway, it seems that this overload of `IO::read` is not used anymore. Why not simply get rid of it?

**Comment by araujoms** [comment]
It seems that the code is counting, but the variable type is a bool, and with the similar variable LP_ANonZeroCount they assign it to true, so I thought this would be the best solution to LP_CNonZeroCount as well.

In any case, this code is clearly a mess, and since it's not used anyway the best remedy is indeed to delete it.

**Comment by denisrosset** [comment]
It seems that the code is actually "counting" using a bool, because of the name of the variable (count non zeros).

But anyway, it seems that this overload of `IO::read` is not used anymore. Why not simply get rid of it?

**Comment by denisrosset** [comment]
@araujoms Would you like to update the PR and I merge it?

**Comment by araujoms** [comment]
sure, done.

**Comment by araujoms** [comment]
hello?

**Pull request closed without merging**
